NTLABaiTapThucHanh613/NTLABaiTapThucHanh613/Models/HangHoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NTLABaiTapThucHanh613.Models
{
    [Table("HangHoa")]
    public class HangHoa
    {
        [Key]
        [Display(Name = "Mã Hàng")]
        [Required(ErrorMessage = "Mã Hàng không được bỏ trống")]
        public string MaHang { get; set; }


        [Required(ErrorMessage = "Tên Hàng không được bỏ trống")]
        [Display(Name = "Tên Hàng")]
        [MinLength(3)]
        public string TenHang { get; set; }


        [Required(ErrorMessage = "Số Lượng không được bỏ trống")]
        [Display(Name = "Số Lượng")]
        public int SoLuong { get; set; }


        [Required(ErrorMessage = "Đơn Giá không được bỏ trống")]
        [Display(Name = "Đơn Giá")]
        public int DonGia { get; set; }
        public ICollection<XuatKho> XuatKho { get; set; }
        public ICollection<NhapKho> NhapKho { get; set; }
    }
}

NTLABaiTapThucHanh613/NTLABaiTapThucHanh613/Areas/Client/Controllers/HangHoasController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NTLABaiTapThucHanh613.Models;

namespace NTLABaiTapThucHanh613.Areas.Client.Controllers
{
    public class HangHoasController : Controller
    {
        private LTQLDB db = new LTQLDB();
        AutoGenerateKey aukey = new AutoGenerateKey();

        // GET: Client/HangHoas
        public ActionResult Index()
        {
            return View(db.HangHoas.ToList());
        }

        public ActionResult Upfile()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Upfile (HttpPostedFileBase file)
        {
            string filePath = string.Empty;
            if (file !=null)
            {
                string path = Server.MapPath("~/Uploads/");
                filePath = path + Path.GetFileName(file.FileName);
                string extension = Path.GetExtension(file.FileName);
                file.SaveAs(filePath);
                string conString = string.Empty;
                switch (extension)
                {
                    case ".xls":
                        conString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source =" + filePath + ";Extended Properties='Excel 8.0;HDR=YES' ";
                        break;
                    case ".xlsx":
                        conString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source =" + filePath + ";Extended Properties='Excel 12.0;HDR=YES' ";
                        break;
                }
                DataTable dt = new DataTable();
                conString = string.Format(conString, filePath);
                using (OleDbConnection connExcel = new OleDbConnection(conString))
                {
                    using (OleDbCommand cmdExcel = new OleDbCommand())
                    {
                        using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                        {
                            cmdExcel.Connection = connExcel;
                            connExcel.Open();
                            DataTable dtExcelShema;
                            dtExcelShema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                            string sheetName = dtExcelShema.Rows[0]["TABLE_NAME"].ToString();
                            connExcel.Close();

                            connExcel.Open();
                            cmdExcel.CommandText = "SELECT * From[" + sheetName + "]";
                            odaExcel.SelectCommand = cmdExcel;
                            odaExcel.Fill(dt);
                            connExcel.Close();

                        }    
                    }    
                }
                conString = @"data source=DESKTOP-S60DTPV;initial catalog=LTQLDB;integrated security=True";
                using (SqlConnection con = new SqlConnection(conString)) 
                {
                    using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
                    {
                        
                        sqlBulkCopy.DestinationTableName = "dbo.HangHoa";
                        sqlBulkCopy.ColumnMappings.Add("MaHang", "MaHang");
                        sqlBulkCopy.ColumnMappings.Add("TenHang", "TenHang");
                        sqlBulkCopy.ColumnMappings.Add("SoLuong", "SoLuong");
                        sqlBulkCopy.ColumnMappings.Add("DonGia", "DonGia");
                        sqlBulkCopy.ColumnMappings.Add("ThanhTien", "ThanhTien");
                        con.Open();
                        sqlBulkCopy.WriteToServer(dt);
                        con.Close();

                    }
                } 
                                    
            } 
            ViewBag.Success = "Thêm dữ liệu thành công";
            return View();
        }

        // GET: Client/HangHoas/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangHoa hangHoa = db.HangHoas.Find(id);
            if (hangHoa == null)
            {
                return HttpNotFound();
            }
            return View(hangHoa);
        }

        // GET: Client/HangHoas/Create
      
        public ActionResult Create()
        {
            if (db.HangHoas.OrderByDescending(m => m.MaHang).Count() == 0)
            {
                var newID = "MHH001";
                ViewBag.NewMHHID = newID;
            }
            else
            {
                var MHHID = db.HangHoas.OrderByDescending(m => m.MaHang).FirstOrDefault().MaHang;
                var newID = aukey.GenerateKey(MHHID);
                ViewBag.NewMHHID = newID;
            }
            return View();

        }

        // POST: Client/HangHoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaHang,TenHang,SoLuong,DonGia")] HangHoa hangHoa)
        {
            if (ModelState.IsValid)
            {
                db.HangHoas.Add(hangHoa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hangHoa);
        }

        // GET: Client/HangHoas/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangHoa hangHoa = db.HangHoas.Find(id);
            if (hangHoa == null)
            {
                return HttpNotFound();
            }
            return View(hangHoa);
        }

        // POST: Client/HangHoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaHang,TenHang,SoLuong,DonGia")] HangHoa hangHoa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hangHoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hangHoa);
        }

        // GET: Client/HangHoas/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangHoa hangHoa = db.HangHoas.Find(id);
            if (hangHoa == null)
            {
                return HttpNotFound();
            }
            return View(hangHoa);
        }

        // POST: Client/HangHoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            HangHoa hangHoa = db.HangHoas.Find(id);
            db.HangHoas.Remove(hangHoa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        

    }
}

NTLABaiTapThucHanh613/NTLABaiTapThucHanh613/Controllers/HangHoasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NTLABaiTapThucHanh613.Models;

namespace NTLABaiTapThucHanh613.Controllers
{
    public class HangHoasController : Controller
    {
        private LTQLDB db = new LTQLDB();
        AutoGenerateKey Aukey = new AutoGenerateKey();

        // GET: HangHoas
        public ActionResult Index()
        {
            return View(db.HangHoas.ToList());
        }

        // GET: HangHoas/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangHoa hangHoa = db.HangHoas.Find(id);
            if (hangHoa == null)
            {
                return HttpNotFound();
            }
            return View(hangHoa);
        }

        // GET: HangHoas/Create
        public ActionResult Create()
        {

            if (db.HangHoas.OrderByDescending(m => m.MaHang).Count() == 0)
            {
                var newID = "MHH001";
                ViewBag.NewMHHID = newID;
            }
            else
            {
                var MHHID = db.HangHoas.OrderByDescending(m => m.MaHang).FirstOrDefault().MaHang;
                var newID = Aukey.GenerateKey(MHHID);
                ViewBag.NewMHHID = newID;
            }
            return View();

        }

        // POST: HangHoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaHang,TenHang,SoLuong,DonGia")] HangHoa hangHoa)
        {
            if (ModelState.IsValid)
            {
                db.HangHoas.Add(hangHoa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hangHoa);
        }

        // GET: HangHoas/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangHoa hangHoa = db.HangHoas.Find(id);
            if (hangHoa == null)
            {
                return HttpNotFound();
            }
            return View(hangHoa);
        }

        // POST: HangHoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaHang,TenHang,SoLuong,DonGia")] HangHoa hangHoa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hangHoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hangHoa);
        }

        // GET: HangHoas/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangHoa hangHoa = db.HangHoas.Find(id);
            if (hangHoa == null)
            {
                return HttpNotFound();
            }
            return View(hangHoa);
        }

        // POST: HangHoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            HangHoa hangHoa = db.HangHoas.Find(id);
            db.HangHoas.Remove(hangHoa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NTLABaiTapThucHanh613/NTLABaiTapThucHanh613/Areas/Client/Views/HangHoas/Create.cshtml
@model NTLABaiTapThucHanh613.Models.HangHoa

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Client/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HangHoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="MaHang" value="@ViewBag.NewMHHID" class="form-control" />
                @Html.ValidationMessageFor(model => model.MaHang, "", new { @class = "text-danger" })
            </div>
        </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenHang, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenHang, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenHang, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NTLABaiTapThucHanh613/NTLABaiTapThucHanh613/Areas/Client/Views/HangHoas/Delete.cshtml
@model NTLABaiTapThucHanh613.Models.HangHoa

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Client/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HangHoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NTLABaiTapThucHanh613/NTLABaiTapThucHanh613/Areas/Client/Views/HangHoas/Details.cshtml
@model NTLABaiTapThucHanh613.Models.HangHoa

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Client/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>HangHoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaHang }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NTLABaiTapThucHanh613/NTLABaiTapThucHanh613/Areas/Client/Views/HangHoas/Edit.cshtml
@model NTLABaiTapThucHanh613.Models.HangHoa

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Client/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HangHoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaHang)

        <div class="form-group">
            @Html.LabelFor(model => model.TenHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NTLABaiTapThucHanh613/NTLABaiTapThucHanh613/Areas/Client/Views/HangHoas/Index.cshtml
@model IEnumerable<NTLABaiTapThucHanh613.Models.HangHoa>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Client/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoLuong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DonGia)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenHang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuong)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DonGia)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaHang }) |
            @Html.ActionLink("Details", "Details", new { id=item.MaHang }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaHang })
        </td>
    </tr>
}

</table>

NTLABaiTapThucHanh613/NTLABaiTapThucHanh613/Areas/Client/Views/HangHoas/Upfile.cshtml
@{
    ViewBag.Title = "Upfile";
    Layout = "~/Areas/Client/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Upfile", "HangHoas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" />
    <br />
    <input type="Submit" value="Import to DB" class="btn btn-primary" />

}
<br />
<div>
    @ViewBag.Success
</div>